name: node

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Build production
      - run: npm run build:prod
      - name: Install modules
      - run: npm ci
      - name: Testing Linter
      - run: npm run lint:ts
      - name: Testing Stiling
      - run: npm run lint:scss
      - name: Unit testing
      - run: npm run test:unit

