name: node
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm i
      - name: Build production project
        run: npm run build:prod
      - name: Testing Linter
        run: npm run lint:ts
      - name: Testing Stiling
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Build Storybook
        run: npm run storybook:build
      - name: Run screenshot testing
        run: npm run test:ui:ci

